
format_version: 2
pipelines:
  Build_Java_Project:
    group: InfrastructurePipelines
#    materials:
#      backend:
#        git: http://git-repo:3000/gogs/sample-pipeline-backend.git
#        branch: master
#      CommitPhasePassed:
#        pipeline: Backend_CommitPhase
#        stage: Push_To_Registry
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Docker_Compose_Up:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/bash
                    arguments:
                      - ./pipeline/scripts/java_build_project.sh
      - E2E_Tests:
          jobs:
            Run_E2E_Tests:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/bash
                    arguments:
                      - ./pipeline/scripts/run_tests.sh
